controller_manager:
    ros__parameters:
        use_sim_time: true

        update_rate: 400

        effort_controller:
            type: effort_controllers/JointGroupEffortController
            
        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        imu_sensor_broadcaster:
            type: imu_sensor_broadcaster/IMUSensorBroadcaster

        whole_body_controller:
            type: hqp_controller/HQPController

        static_walk_planner:
            type: static_walk_planner/SWPController

        lip_planner:
            type: lip_walking_trot_planner/LIPController


joint_state_broadcaster:
    ros__parameters:
        joints:
            - FL_HAA
            - FL_HFE
            - FL_KFE
            - FR_HAA
            - FR_HFE
            - FR_KFE
            - HL_HAA
            - HL_HFE
            - HL_KFE
            - HR_HAA
            - HR_HFE
            - HR_KFE
        interfaces:
            - position
            - velocity
            - effort


imu_sensor_broadcaster:
    ros__parameters:
        sensor_name: imu_sensor
        frame_id: base


whole_body_controller:
    ros__parameters:
        use_sim_time: true

        robot_name: solo12
        sample_time: 0.0025

        use_estimator: false        # ! Must be the same as the use_estimator in the planner
        initialization_time: 1.5

        q1:
            -  0.0
            -  0.3
            - -0.6
            -  0.0
            -  0.3
            - -0.6
            -  0.0
            - -0.3
            -  0.6
            -  0.0
            - -0.3
            -  0.6

        PD_proportional: 
            - 5.
        PD_derivative:
            -  0.5
            -  0.5
            -  0.05
            -  0.5
            -  0.5
            -  0.05
            -  0.5
            -  0.5
            -  0.05
            -  0.5
            -  0.5
            -  0.05

        logging: true

        joints:
            - FL_HAA
            - FL_HFE
            - FL_KFE
            - FR_HAA
            - FR_HFE
            - FR_KFE
            - HL_HAA
            - HL_HFE
            - HL_KFE
            - HR_HAA
            - HR_HFE
            - HR_KFE

        contact_constraint_type: rigid

        shift_base_height: false
        
        tau_max: 2.7
        mu: 1.0
        Fn_max: 25.
        Fn_min: 2.

        kp_b_pos:
            - 100.
            - 100.
            - 100.
        kd_b_pos:
            - 10.
            - 10.
            - 10.

        kp_b_ang:
            - 150.
            - 150.
            - 150.
        kd_b_ang:
            - 35.
            - 35.
            - 35.

        kp_s_pos:
            - 1800.
            - 1800.
            - 900.
        kd_s_pos:
            - 30.
            - 30.
            - 90.
            
        kp_terr:
            - 1000.
            - 1000.
            - 1000.
        kd_terr:
            - 1000.
            - 1000.
            - 1000.

        kc_v:
            - 0.
            - 0.
            - 0.

        regularization: 1e-6


static_walk_planner:
    ros__parameters:
        use_sim_time: true

        use_estimator: false        # ! Must be the same as the use_estimator in the whole_body_controller
        initialization_time: 1.

        sample_time: 0.0025
        init_phase: 2.0

        gait_pattern:
            - LF
            - RH
            - RF
            - LH

        cycle_duration: 3.0
        step_duty_factor: 0.7

        step_length: 0.15
        step_height: 0.075
        desired_foot_penetration: 0.00
        step_horizontal_delay: 0.1
        foot_trajectory_type: splines

        desired_base_height: 0.26
        initial_base_height: 0.31

        terrain_height: 0.0
        terrain_penetration: 0.0

        initial_position:
            - 0.
            - 0.
        leg_position: 
            - 0.165
            - 0.13
        base_oscillation: 
            - 0.04
            - 0.02


lip_planner:
    ros__parameters:
        use_sim_time: true

        zero_time: 1.0
        init_time: 1.0

        sample_time: 0.0025

        step_reachability: 0.15
        feet_theta: 0.7
        feet_r: 0.25
        base_height: 0.22

        max_fixed_steps: 6

        interpolation_method: spline3   # must be in [spline3, spline5, cycloid]
        step_duration: 0.2
        step_height: 0.05
        step_horizontal_phase_delay: 0.0
        foot_penetration: -0.025

        acc_filter_order: 2
        acc_filter_beta: 0.99

        correct_with_terrain_penetrations: true
        gain_correction_with_terrain_penetrations: 0.5

        interpolate_swing_feet_from_current_position: false