controller_manager:
    ros__parameters:
        update_rate: 200

        effort_controller:
            type: effort_controllers/JointGroupEffortController
            
        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        imu_sensor_broadcaster:
            type: imu_sensor_broadcaster/IMUSensorBroadcaster

        whole_body_controller:
            type: hqp_controller/HQPController

        planner:
            type: static_walk_planner/SWPController


joint_state_broadcaster:
    ros__parameters:
        joints:
            - FL_HAA
            - FL_HFE
            - FL_KFE
            - FR_HAA
            - FR_HFE
            - FR_KFE
            - HL_HAA
            - HL_HFE
            - HL_KFE
            - HR_HAA
            - HR_HFE
            - HR_KFE
        interfaces:
            - position
            - velocity
            - effort


effort_controller:
    ros__parameters:
        joints:
            - FL_HAA
            - FL_HFE
            - FL_KFE
            - FR_HAA
            - FR_HFE
            - FR_KFE
            - HL_HAA
            - HL_HFE
            - HL_KFE
            - HR_HAA
            - HR_HFE
            - HR_KFE
        command_interfaces:
            - effort
        state_interfaces:
            - position
            - velocity
            - effort

        state_publish_rate:  200.0 # Defaults to 50
        action_monitor_rate: 200.0 # Defaults to 20


imu_sensor_broadcaster:
    ros__parameters:
        sensor_name: imu_sensor
        frame_id: base


whole_body_controller:
    ros__parameters:
        robot_name: solo12
        sample_time: 0.0025

        use_estimator: false        # ! Must be the same as the use_estimator in the planner
        initialization_time: 0.     # ! Must be the same as the initialization_time in the planner

        PD_proportional: 5.
        PD_derivative: 0.05

        logging: true

        joints:
            - FL_HAA
            - FL_HFE
            - FL_KFE
            - FR_HAA
            - FR_HFE
            - FR_KFE
            - HL_HAA
            - HL_HFE
            - HL_KFE
            - HR_HAA
            - HR_HFE
            - HR_KFE

        contact_constraint_type: soft_kv
        tau_max: 2.7
        mu: 0.6
        Fn_max: 10.
        Fn_min: 2.

        kp_b_pos:
            - 50.
            - 50.
            - 50.
        kd_b_pos:
            - 20.
            - 20.
            - 20.

        kp_b_ang:
            - 500.
            - 500.
            - 500.
        kd_b_ang:
            - 100.
            - 100.
            - 100.

        kp_s_pos:
            - 150.
            - 150.
            - 150.
        kd_s_pos:
            - 10.
            - 10.
            - 10.
            
        kp_terr:
            - 1000.
            - 1000.
            - 1000.
        kd_terr:
            - 1000.
            - 1000.
            - 1000.


planner:
    ros__parameters:
        use_estimator: false            # ! Must be the same as the use_estimator in the whole_body_controller
        initialization_time: 0.      # ! Must be the same as the initialization_time in the whole_body_controller

        sample_time: 0.005
        init_phase: 0.4
        gait_pattern:
            - LF
            - RH
            - RF
            - LH
        cycle_duration: 2.
        step_duty_factor: 0.7
        step_length: 0.175
        step_height: 0.075
        desired_foot_penetration: 0.01
        desired_base_height: 0.26
        initial_base_height: 0.33
        initial_position:
            - 0.
            - 0.
        leg_position: 
            - 0.165
            - 0.11
        base_oscillation: 
            - 0.03
            - 0.02