<?xml version="1.0" encoding="utf-8"?>
<robot name="ground_plane" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="length" default="4"/>
    <xacro:property name="width" default="100"/>

    <xacro:property name="roll"  default="0"/>
    <xacro:property name="pitch" default="0"/>
    <xacro:property name="yaw"   default="0"/>

    <xacro:property name="pitch_increase" default="-0.05"/>

    <xacro:property name="x" default="0"/>
    <xacro:property name="y" default="0"/>
    <xacro:property name="z" default="-1"/>

    <xacro:macro name="link" params="id">
        <joint name="ground_plane_link_${id-1}_to_ground_plane_link_${id}" type="fixed">
            <xacro:if value="${id - 1 == 1}">
                <parent link="ground_plane_link"/>
            </xacro:if>
            <xacro:if value="${id - 1 != 1}">
                <parent link="ground_plane_link_${id-1}"/>
            </xacro:if>
            <xacro:if value="${id == 1}">
                <child link="ground_plane_link"/>
            </xacro:if>
            <xacro:if value="${id != 1}">
                <child link="ground_plane_link_${id}"/>
            </xacro:if>
            <origin xyz="${length/2} 0 0" rpy="${roll} ${pitch_increase} ${yaw}"></origin>
        </joint>
        <link name="ground_plane_link_${id}">
            <visual>
                <origin rpy="${roll} ${pitch} ${yaw}" xyz="${length/2} ${y} ${z}"/>
                <geometry>
                    <box size="${length} ${width} 2"/>
                </geometry>
    
                <xacro:if value="${id % 2 == 0}">
                    <material name="dark_grey">
                        <color rgba="0.5 0.5 0.5 1.0"/>
                    </material>
                </xacro:if>
                <xacro:if value="${id % 2 != 0}">
                    <material name="grey">
                        <color rgba="0.8 0.8 0.8 1.0"/>
                    </material>
                </xacro:if>
                
            </visual>
            <collision>
                <origin rpy="${roll} ${pitch} ${yaw}" xyz="${length/2} ${y} ${z}"/>
                <geometry>
                    <box size="${length} ${width} 2"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <mass value="1"/>
                <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
            </inertial>
        </link>

        <gazebo reference="ground_plane_link_${id-1}_to_ground_plane_link_${id}">
            <preserveFixedJoint>true</preserveFixedJoint>
        </gazebo>

        <gazebo reference="ground_plane_link_${id}">
            <xacro:if value="${id % 2 == 0}">
                <material>Gazebo/DarkGrey</material>
            </xacro:if>
            <xacro:if value="${id % 2 != 0}">
                <material>Gazebo/Grey</material>
            </xacro:if>
            <kp>1e6</kp>
            <kd>1e2</kd>
        </gazebo>
    </xacro:macro>

    <gazebo>
        <static>true</static>
    </gazebo>

    <link name="ground_plane_link">
        <visual>
            <origin rpy="${roll} ${pitch} ${yaw}" xyz="${x} ${y} ${z}"/>
            <geometry>
                <box size="${length} ${width} 2"/>
            </geometry>

            <material name="grey">
                <color rgba="0.8 0.8 0.8 1.0"/>
            </material>
        </visual>
        <collision>
            <origin rpy="${roll} ${pitch} ${yaw}" xyz="${x} ${y} ${z}"/>
            <geometry>
                <box size="${length} ${width} 2"/>
            </geometry>
        </collision>
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="1"/>
            <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
        </inertial>
    </link>
    <xacro:link id="2"/>
    <xacro:link id="3"/>
    <xacro:link id="4"/>
    <xacro:link id="5"/>
    <xacro:link id="6"/>

    <joint name="ground_plane_link_to_ground_plane_link_inertia" type="fixed">
        <parent link="ground_plane_link"/>
        <child link="ground_plane_link_inertia"/>
    </joint>
    <link name="ground_plane_link_inertia">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="1"/>
            <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
        </inertial>
    </link>

    <gazebo reference="ground_plane_link">
        <material>Gazebo/Grey</material>
        <kp>1e6</kp>
        <kd>1e2</kd>
    </gazebo>
    
</robot>