controller_manager:
    ros__parameters:
        update_rate: 100

        effort_controllers:
            type: effort_controllers/JointGroupEffortController
            
        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        imu_sensor_broadcaster:
            type: imu_sensor_broadcaster/IMUSensorBroadcaster
            
effort_controllers:
    ros__parameters:
        joints:
            - LF_HAA
            - LF_HFE
            - LF_KFE
            - LH_HAA
            - LH_HFE
            - LH_KFE
            - RF_HAA
            - RF_HFE
            - RF_KFE
            - RH_HAA
            - RH_HFE
            - RH_KFE
        command_interfaces:
            - effort
        state_interfaces:
            - position
            - velocity
            - effort

        state_publish_rate:  200.0 # Defaults to 50
        action_monitor_rate: 200.0 # Defaults to 20

imu_sensor_broadcaster:
    ros__parameters:
        sensor_name: imu_sensor
        frame_id: base