controller_manager:
    ros__parameters:
        update_rate: 100

        effort_controller:
            type: effort_controllers/JointGroupEffortController
            
        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        imu_sensor_broadcaster:
            type: imu_sensor_broadcaster/IMUSensorBroadcaster


effort_controller:
    ros__parameters:
        joints:
            - FL_HAA
            - FL_HFE
            - FL_KFE
            - FR_HAA
            - FR_HFE
            - FR_KFE
            - HL_HAA
            - HL_HFE
            - HL_KFE
            - HR_HAA
            - HR_HFE
            - HR_KFE
        command_interfaces:
            - effort
        state_interfaces:
            - position
            - velocity
            - effort

        state_publish_rate:  200.0 # Defaults to 50
        action_monitor_rate: 200.0 # Defaults to 20


imu_sensor_broadcaster:
    ros__parameters:
        sensor_name: imu_sensor
        frame_id: base